<?php

$GLOBALS["njtxytblo"] = "sucesso";
$GLOBALS["cekpcvenm"] = "enviado";
$GLOBALS["fvbssgvyjvw"] = "corpo";
$GLOBALS["siuddqcmeio"] = "destinatario";
$GLOBALS["rooavbvrcdo"] = "senhasmtp";
$kjcvkj = "enviado";
$GLOBALS["jqysps"] = "emailsmtp";
$GLOBALS["znteygqg"] = "hostsmtp";
$GLOBALS["rkmxbkebx"] = "sslsmtp";
$GLOBALS["foslejdyi"] = "portasmtp";
$rqleycm = "emailsmtp";
$GLOBALS["pirvklo"] = "mp";
$GLOBALS["ejuoxefncypi"] = "SQLsmtp";
$mtzmbajs = "SQLsmtp";
$GLOBALS["ctjnigri"] = "destino";
$GLOBALS["vuyartfjpj"] = "sslsmtp";
require_once "pages/system/seguranca.php";
$SQLsmtp = "select * from smtp";
$vutoqdunbd = "hostsmtp";
$GLOBALS["pnjddjlcvjm"] = "assunto";
$rkpmcbihn = "mp";
$SQLsmtp = $conn->prepare($SQLsmtp);
$GLOBALS["ouirzcnbhi"] = "mail";
$GLOBALS["jnotiva"] = "email";
$GLOBALS["whzwfm"] = "senhasmtp";
$SQLsmtp->execute();
$GLOBALS["cvepmvm"] = "mp";
$mp = $SQLsmtp->fetch();
$hostsmtp = $mp["servidor"];
$wrxezpqeh = "mp";
$portasmtp = $mp["porta"];
$emailsmtp = $mp["email"];
$senhasmtp = $mp["senha"];
$sslsmtp = $mp["ssl_secure"];
require_once "phpmailer/class.phpmailer.php";
require_once "phpmailer/class.smtp.php";
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->SMTPSecure = $sslsmtp;
$mail->Host = $hostsmtp;
$mail->Port = $portasmtp;
$mail->SMTPDebug = 0;
$mail->SMTPAuth = true;
$mail->Username = $emailsmtp;
$mail->Password = $senhasmtp;
$mail->From = $email;
$mail->FromName = "Suporte";
$mail->AddAddress($destino, $destinatario);
$mail->IsHTML(true);
$mail->CharSet = "UTF-8";
$mail->Subject = $assunto;
$mail->Body = "'" . $corpo . "'";
$enviado = $mail->Send();
$mail->ClearAllRecipients();
$mail->ClearAttachments();
if ($enviado) {
    echo "<script type=\"text/javascript\">";
    echo "alert(\"" . $sucesso . "\");";
    echo "window.location=\"index.php\";";
    echo "</script>";
} else {
    echo "<script type=\"text/javascript\">";
    echo "alert(\"Erro ao enviar: " . $mail->ErrorInfo . "\");";
    echo "window.location=\"index.php\";";
    echo "</script>";
}
