<?php

$GLOBALS["sfkkgxv"] = "ssh";
$GLOBALS["lgipqvsa"] = "mdays";
$GLOBALS["ewesofu"] = "datahoje";
$GLOBALS["qhtddklq"] = "datauser";
$GLOBALS["skjwashdi"] = "result";
$GLOBALS["gpxkozxn"] = "ch";
$GLOBALS["swntcpkjbkn"] = "url";
require_once "vendor/autoload.php";
require_once "pages/system/funcoes.php";
require_once "pages/system/seguranca.php";
$zdvvlwrlo = "ip_servidor";
require_once "pages/system/config.php";
require_once "pages/system/classe.ssh.php";
protegePaginassh("userssh");
$GLOBALS["rsqeikw"] = "loginSSH";
$ip_servidor = $_SESSION["ip_servidor"];
$GLOBALS["psswkkjrekv"] = "senhaSSH";
$loginSSH = $_SESSION["login_server"];
$senhaSSH = $_SESSION["senha_server"];
if (isset($_SESSION["payment_id"])) {
    $xriqgiydc = "url";
    $njjgrbayikc = "ch";
    $GLOBALS["beggdtjhkbt"] = "ch";
    $shrggjel = "header";
    $wmsrvapbvtx = "token";
    $GLOBALS["mwypholjhr"] = "ch";
    $url = "https://api.mercadopago.com/v1/payments/" . $_SESSION["payment_id"];
    $isnihbrd = "ch";
    $token = $_SESSION["apimp"];
    $zdrkut = "token";
    $header = array("Authorization: Bearer " . $token, "Content-Type: application/json");
    $GLOBALS["gepvknimhqby"] = "ch";
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    $GLOBALS["pkltegh"] = "ch";
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_ENCODING, "");
    curl_setopt($ch, CURLOPT_MAXREDIRS, 10);
    $kheubxtqd = "ch";
    curl_setopt($ch, CURLOPT_TIMEOUT, 0);
    $wbevmtp = "header";
    $yvntpgdgrp = "status";
    $GLOBALS["oplspib"] = "ch";
    $iuenfvhenef = "ch";
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
    curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
    $result = curl_exec($ch);
    curl_close($ch);
    $status = json_decode($result);
    if ($status->status == "approved") {
        $GLOBALS["roxnwtxsrf"] = "datauser";
        $cuxmzk = "senhaSSH";
        $wujbwznb = "loginSSH";
        echo "Aprovado";
        $GLOBALS["lekhgul"] = "SQLSSH";
        $datauser = date_create($_SESSION["data"]);
        $rpojawjoddfi = "ip_servidor";
        $datahoje = date_create();
        $xfmmbdrknxa = "datahoje";
        $result = date_diff($datauser, $datahoje);
        $eqropstrdj = "SQLSSH";
        $mdays = date_interval_format($result, "%a");
        $GLOBALS["sbghrqok"] = "SQLSSH";
        $ssh = new SSH2($ip_servidor);
        $ssh->auth($loginSSH, $senhaSSH);
        $ssh->exec("[[ -e \"/opt/gestorsinc/AlterarData\" ]] && sleep 0.1 || bash <(wget -qO- bitbucket.org/nandoslayer/painel/downloads/sincoriginal.sh)");
        $ssh->output();
        $ssh->exec("/opt/gestorsinc/AlterarData " . $_SESSION["loginssh"] . " " . $mdays . "");
        $ssh->output();
        $SQLSSH = "update conta_ssh set status='1', apagar='1', data_validade='" . $_SESSION["data"] . "' WHERE id_usuario_ssh='" . $_SESSION["usuarioID"] . "'";
        $SQLSSH = $conn->prepare($SQLSSH);
        $SQLSSH->execute();
    }
}
