<?php

$GLOBALS["okogdloocrzu"] = "smtp";
$GLOBALS["xtwamvv"] = "smtp";
$GLOBALS["vcymaxerdvje"] = "conta";
$GLOBALS["nghanhoiuaw"] = "buscasmtp";
$GLOBALS["snvbmani"] = "buscasmtp";
$baueglz = "buscasmtp";
if (basename($_SERVER["REQUEST_URI"]) === basename("/var/www/html/1etapasmtp.php")) {
    exit("<h1>ERROR 404</h1>Entre em contato conosco e envie detalhes.");
}
$iteymzhhpvr = "smtp";
protegePagina("donoadmin");
${$GLOBALS["nghanhoiuaw"]} = "SELECT * FROM smtp WHERE usuario_id='" . $_SESSION["usuarioID"] . "'";
${$baueglz} = $conn->prepare(${$GLOBALS["snvbmani"]});
$GLOBALS["gjohgmp"] = "smtp";
$buscasmtp->execute();
${$iteymzhhpvr} = $buscasmtp->fetch();
${$GLOBALS["vcymaxerdvje"]} = $buscasmtp->rowCount();
echo "<!-- Input with Icons start -->\n<section id=\"input-with-icons\">\n    <div class=\"row match-height\">\n        <div class=\"col-12\">\n            <div class=\"card\">\n                <div class=\"card-header\">\n                    <h1 class=\"card-title font-medium-2\"><i class=\"fad fa-at text-info font-large-1\"></i> Configurar Servidor de Email</h1>\n                </div>\n                <div class=\"card-content\">\n                    <form action=\"pages/email/configurasmtp.php\" method=\"POST\" role=\"form\">\n                        <div class=\"card-body\">\n                            <div class=\"row\">\n                                <div class=\"col-sm-6 col-12\">\n                                    <div class=\"mb-0\">\n                                        Servidor\n                                    </div>\n                                    <fieldset class=\"form-group position-relative has-icon-left\">\n                                        <input required=\"required\" type=\"text\" value=\"";
echo ${$GLOBALS["gjohgmp"]}["servidor"];
echo "\" class=\"form-control\" id=\"servidor\" name=\"servidor\" placeholder=\"Ex: smtp.gmail.com\">\n                                        <div class=\"form-control-position\">\n                                            <i class=\"fad fa-at\"></i>\n                                        </div>\n                                    </fieldset>\n                                </div>\n                                <div class=\"col-sm-6 col-12\">\n                                    <div class=\"mb-1\">\n                                        <div class=\"mb-0\">\n                                            Porta\n                                        </div>\n                                        <fieldset class=\"form-group position-relative\">\n                                            <input required=\"required\" type=\"text\" value=\"";
echo ${$GLOBALS["xtwamvv"]}["porta"];
echo "\" class=\"form-control\" id=\"porta\" name=\"porta\" placeholder=\"Ex: 465 SSL ou 587 TLS\">\n                                            <div class=\"form-control-position\">\n                                                <i class=\"fad fa-at\"></i>\n                                            </div>\n                                        </fieldset>\n                                    </div>\n                                </div>\n                                <div class=\"col-sm-6 col-12\">\n                                    <div class=\"mb-1\">\n                                        <div class=\"mb-0\">\n                                            SSL ou TLS\n                                        </div>\n                                        <fieldset class=\"form-group position-relative has-icon-left input-divider-left\">\n                                            <input required=\"required\" type=\"text\" value=\"";
echo ${$GLOBALS["okogdloocrzu"]}["ssl_secure"];
echo "\" class=\"form-control\" id=\"ssl\" name=\"ssl\" placeholder=\"Ex: SSL ou TLS\">\n                                            <div class=\"form-control-position\">\n                                                <i class=\"fad fa-at\"></i>\n                                            </div>\n                                        </fieldset>\n                                    </div>\n                                </div>\n                                <div class=\"col-sm-6 col-12\">\n                                    <div class=\"mb-1\">\n                                        <div class=\"mb-0\">\n                                            Email\n                                        </div>\n                                        <fieldset class=\"form-group position-relative input-divider-right\">\n                                            <input required=\"required\" type=\"text\" value=\"";
echo ${$GLOBALS["okogdloocrzu"]}["email"];
echo "\" class=\"form-control\" id=\"email\" name=\"email\" placeholder=\"Email do servidor\">\n                                            <div class=\"form-control-position\">\n                                                <i class=\"fad fa-at\"></i>\n                                            </div>\n                                        </fieldset>\n                                    </div>\n                                </div>\n                                <div class=\"col-12\">\n                                    <div class=\"mb-2\">\n                                        <div class=\"mb-0\">\n                                            Senha\n                                        </div>\n                                        <fieldset class=\"form-group position-relative input-divider-right\">\n                                            <input class=\"form-control\" type=\"password\" value=\"";
echo ${$GLOBALS["okogdloocrzu"]}["senha"];
echo "\" id=\"senha\" name=\"senha\" placeholder=\"Senha do Email\">\n                                            <div class=\"form-control-position\">\n                                                <i class=\"fad fa-key-skeleton\"></i>\n                                            </div>\n                                        </fieldset>\n                                    </div>\n                                </div>\n                                <div class=\"col-sm-12 col-12 text-center\">\n                                    <button type=\"submit\" class=\"btn btn-success\">Salvar</button>\n                                    <button type=\"reset\" class=\"btn btn-danger\">Limpar</button>\n                                </div>\n                            </div>\n                        </div>\n                    </form>\n                </div>\n            </div>\n        </div>\n    </div>\n</section>\n<!-- Input with Icons end -->\n";
