<?php

$GLOBALS["ngpsvugt"] = "isp";
$GLOBALS["krrjuviplwwn"] = "linha";
$GLOBALS["nolellyogdjk"] = "administrador";
$GLOBALS["xhiypauks"] = "SQLAdministrador";
require_once "../pages/system/funcoes.php";
$tuurhsuccsde = "SQLAdministrador";
$rjwtjegx = "administrador";
require_once "../pages/system/seguranca.php";
require_once "../pages/system/config.php";
require_once "../pages/system/classe.ssh.php";
$SQLAdministrador = "SELECT * FROM admin WHERE id_administrador = '1'";
$SQLAdministrador = $conn->prepare($SQLAdministrador);
$SQLAdministrador->execute();
$administrador = $SQLAdministrador->fetch();
echo "<!DOCTYPE html>\n<html class=\"loading bordered-layout\" lang=\"pt-br\" data-layout=\"bordered-layout\" data-textdirection=\"ltr\">\n<!-- BEGIN: Head-->\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui\">\n<meta name=\"description\" content=\"Painel de gerenciamento vpn\">\n<meta name=\"keywords\" content=\"vpn, ssh, user, servidor\">\n<meta name=\"author\" content=\"crazy\">\n<title>";
echo $administrador["site"];
echo "</title>\n<link rel=\"apple-touch-icon\" href=\"../app-assets/images/ico/apple-icon-120.png\">\n<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"../app-assets/images/ico/favicon.ico\">\n<link href=\"https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600\" rel=\"stylesheet\">\n<!-- BEGIN: Vendor CSS-->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/vendors/css/vendors.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/vendors/css/animate/animate.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/vendors/css/extensions/sweetalert2.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/plugins/extensions/ext-component-sweet-alerts.css\">\n<!-- BEGIN: Theme CSS-->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/bootstrap.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/bootstrap-extended.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/colors.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/components.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/themes/dark-layout.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/themes/bordered-layout.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/themes/semi-dark-layout.css\">\n<!-- BEGIN: Page CSS-->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/core/menu/menu-types/vertical-menu.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/plugins/forms/form-validation.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../app-assets/css/pages/authentication.css\">\n<!-- END: Page CSS-->\n<!-- BEGIN: Custom CSS-->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../assets/css/style.css\">\n<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js\"></script>\n<!-- END: Custom CSS-->\n</head>\n<!-- BEGIN: Body-->\n<body class=\"vertical-layout vertical-menu-modern blank-page navbar-floating footer-static  \" data-open=\"click\" data-menu=\"vertical-menu-modern\" data-col=\"blank-page\">\n<style>\n@media (max-width: 320px) {\n.reduzcel{\nmax-width:90%;\n}\n}\n</style>\n<section id=\"wrapper\">\n<!-- BEGIN: Content-->\n<div class=\"app-content content \">\n<div class=\"content-overlay\"></div>\n<div class=\"header-navbar-shadow\"></div>\n<div class=\"content-wrapper\">\n<div class=\"content-header row\">\n</div>\n<div class=\"content-body\">\n<div class=\"auth-wrapper auth-basic px-2\">\n<div class=\"auth-inner my-2\">\n<!-- Login basic -->\n<div class=\"card mb-0\">\n<div class=\"card-body\">\n<h2 class=\"text-primary text-center\"><a class=\"nav-link nav-link-style\"><b>";
echo $administrador["site"];
echo "</b></h2></a>\n<br>\n<div align=\"center\" class=\"login-logo\">\n<a ><img src=\"../app-assets/images/pages/Tempo.gif\" width=\"180\" height=\"295\" class=\"reduzcel\" border=\"0\"></a>\n</div>\n<!-- /.login-logo -->\n<div align=\"center\" class=\"login-box-body\">\n<p class=\"login-box-msg\">Tempo de inatividade expirou!<br>Favor entrar com o usu\xc3\xa1rio novamente<br>para realizar nova <b class=\"text-primary\"> sess\xc3\xa3o</b><b>!</b></p>\n<form action=\"validacao.php\" method=\"post\">\n<div class=\"col-12\">\n<div class=\"mb-1\"></div>\n</div>\n<a href=\"../index.php\" class=\"btn btn-primary btn-block\"><b>Voltar</b></a>\n<br>\n<br><br>\n<!-- BEGIN: Footer-->\n<footer class=\"footer footer-static footer-light mt-5\">\n<div class=\"text-center\">\n<p class=\"clearfix blue-grey lighten-2 mb-0\">\n<span class=\"center\">\nVers\xc3\xa3o: ";
echo $linha;
echo "<br>\n<a class=\"text-bold-800 \" href=\"#\" target=\"_blank\">";
echo $administrador["site"];
echo "&copy; <script>\ndocument.write(new Date().getFullYear())\n</script>.</a><br>Todos os direitos reservados.<br>Seu IP: ";
echo pega_ip();
echo "<br>ISP: ";
echo $isp;
echo "</span>\n</p>\n</div>\n</footer>\n<!-- END: Footer-->\n</form>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>\n</div>\n</section>\n<script>\n\$(document).ready(function(){\n\$(\"#minhaPesquisa\").on(\"keyup\", function() {\nvar value = \$(this).val().toLowerCase();\n\$(\"#MeuServidor tr\").filter(function() {\n\$(this).toggle(\$(this).text().toLowerCase().indexOf(value) > -1)\n});\n});\n});\n</script>\n<script>\nif (localStorage.getItem(\"toggled\") === null) {\nlocalStorage.setItem(\"toggled\", \" \");\n}\n\$(\"#dark-layout\").click(function(){\$(\"body\").toggleClass(\"dark-layout\")}),\$(\"body\").toggleClass(localStorage.toggled),\$(\"#dark-layout\").click(function(){\"dark-layout\"!=localStorage.toggled?(\$(\"body\").toggleClass(\"dark-layout\",!0),localStorage.toggled=\"dark-layout\"):(\$(\"body\").toggleClass(\"dark-layout\",!1),localStorage.toggled=\"\")});\nif (localStorage.getItem(\"toggled\") === \"dark-layout\") {\ndocument.getElementById(\"dark-layout\").checked = true;\n} else {\ndocument.getElementById(\"dark-layout\").checked = false;\n}\n</script>\n<!-- BEGIN: Vendor JS-->\n<script src=\"../app-assets/vendors/js/vendors.min.js\"></script>\n<script src=\"../app-assets/vendors/js/charts/apexcharts.min.js\"></script>\n<script src=\"../app-assets/vendors/js/extensions/tether.min.js\"></script>\n<script src=\"../app-assets/js/core/app-menu.js\"></script>\n<script src=\"../app-assets/js/core/app.js\"></script>\n<script src=\"../app-assets/js/scripts/components.js\"></script>\n<script src=\"../app-assets/js/scripts/pages/dashboard-analytics.js\"></script>\n<script src=\"../app-assets/js/scripts/extensions/ext-component-sweet-alerts.js\"></script>\n<script src=\"../app-assets/vendors/js/extensions/sweetalert2.all.min.js\"></script>\n<script src=\"../app-assets/vendors/js/forms/validation/jquery.validate.min.js\"></script>\n<script src=\"../app-assets/js/scripts/pages/auth-login.js\"></script>\n<!-- END: Page JS-->\n</body>\n<!-- END: Body-->\n</html>\n";
