<?php

$GLOBALS["iyvwdogfrgsd"] = "administrador";
$GLOBALS["fggsywmfbp"] = "accessKEY";
$GLOBALS["vpizdyji"] = "totalservidores";
$GLOBALS["mxlagyrkegct"] = "SQLbuscaservidores";
$GLOBALS["mryjijpykjm"] = "SQLbuscarevendedores";
$GLOBALS["qkjyselecacu"] = "SQLbuscaclientes";
$xrgqoes = "procnoticias";
$GLOBALS["yeoitaf"] = "procnoticias";
$GLOBALS["ietdqaeyft"] = "totalclientes";
$cgshjnmhwmc = "administrador";
if (basename($_SERVER["REQUEST_URI"]) === basename("/var/www/html/dados.php")) {
    exit("<h1>ERROR 404</h1>Entre em contato conosco e envie detalhes.");
}
$GLOBALS["kjtddezjxfsj"] = "procnoticias";
protegePagina("donoadmin");
${$GLOBALS["yeoitaf"]} = "select * FROM noticias where status='ativo'";
$javwip = "SQLbuscaclientes";
$jgmboxvl = "SQLbuscaclientes";
$GLOBALS["rfymegokda"] = "SQLbuscarevendedores";
${$xrgqoes} = $conn->prepare(${$GLOBALS["kjtddezjxfsj"]});
$xpofsyzmryli = "SQLbuscaservidores";
$procnoticias->execute();
$inidmmjnpl = "administrador";
$qjutsue = "administrador";
$GLOBALS["cxkoiryemc"] = "totalrevendedores";
${$javwip} = "select * from usuario where tipo='vpn'";
${$jgmboxvl} = $conn->prepare(${$GLOBALS["qkjyselecacu"]});
$SQLbuscaclientes->execute();
${$GLOBALS["ietdqaeyft"]} = $SQLbuscaclientes->rowCount();
${$GLOBALS["mryjijpykjm"]} = "select * from  usuario where tipo='revenda'";
${$GLOBALS["rfymegokda"]} = $conn->prepare(${$GLOBALS["mryjijpykjm"]});
$GLOBALS["qhfqlviaowz"] = "SQLbuscaservidores";
$SQLbuscarevendedores->execute();
${$GLOBALS["cxkoiryemc"]} = $SQLbuscarevendedores->rowCount();
${$GLOBALS["qhfqlviaowz"]} = "select * from  servidor";
${$GLOBALS["mxlagyrkegct"]} = $conn->prepare(${$xpofsyzmryli});
$SQLbuscaservidores->execute();
${$GLOBALS["vpizdyji"]} = $SQLbuscaservidores->rowCount();
echo "<script>\nfunction limite_textarea1(valor) {\nquant = 500;\ntotal = valor.length;\nif(total <= quant) {\nresto = quant - total;\ndocument.getElementById('cont1').innerHTML = resto;\n} else {\ndocument.getElementById('texto1').value = valor.substr(0,quant);\n}\n}\n</script>\n<script>\nfunction limite_textarea2(valor) {\nquant = 500;\ntotal = valor.length;\nif(total <= quant) {\nresto = quant - total;\ndocument.getElementById('cont2').innerHTML = resto;\n} else {\ndocument.getElementById('texto2').value = valor.substr(0,quant);\n}\n}\n</script>\n<!-- Input with Icons start -->\n<section id=\"multiple-column-form\">\n<div class=\"row\">\n<div class=\"col-12\">\n<div class=\"card\">\n<div class=\"card-header\">\n<h4 class=\"card-title\"><a class=\"text-secondary\">Alterar Informa\xc3\xa7\xc3\xb5es admin</a><a class=\"text-danger\"> (Aten\xc3\xa7\xc3\xa3o!)</a></h4>\n</div>\n<div class=\"card-body\">\n<form action=\"pages/admin/alterar.php\" method=\"POST\" role=\"form\">\n<input type=\"hidden\" class=\"form-control\" id=\"segmax\" name=\"segmax\" value=\"";
echo ${$GLOBALS["fggsywmfbp"]};
echo "\">\n<input type=\"hidden\" class=\"form-control\" id=\"ipmax\" name=\"ipmax\" value=\"";
$ciycdceg = "ipdominio";
echo $ipdominio;
echo "\">\n<div class=\"row\">\n<div class=\"col-md-6 col-12\">\n<div class=\"mb-1\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Nome</a></label>\n<div class=\"input-group input-group-merge\">\n<span class=\"input-group-text\"><i data-feather=\"user\"></i></span>\n<input type=\"text\" name=\"nome\" id=\"nome\" class=\"form-control\" minlength=\"5\" maxlength=\"20\" value=\"";
echo ${$GLOBALS["iyvwdogfrgsd"]}["nome"];
echo "\" required>\n</div>\n</div>\n</div>\n<div class=\"col-md-6 col-12\">\n<div class=\"mb-1\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Usu\xc3\xa1rio</a></label>\n<div class=\"input-group input-group-merge\">\n<span class=\"input-group-text\"><i data-feather=\"user-check\"></i></span>\n<input type=\"text\"name=\"idusuario\" id=\"idusuario\" minlength=\"5\" maxlength=\"20\" oninput=\"this.value = this.value.toLowerCase()\" class=\"form-control\"value=\"";
echo ${$qjutsue}["login"];
echo "\" required=\"\">\n</div>\n</div>\n</div>\n<div class=\"col-md-6 col-12\">\n<div class=\"mb-1\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Celular</a></label>\n<div class=\"input-group input-group-merge\">\n<span class=\"input-group-text\"><i data-feather=\"smartphone\"></i></span>\n<input type=\"text\" class=\"form-control\" minlength=\"10\" maxlength=\"11\" id=\"celular\" name=\"celular\" value=\"";
echo ${$inidmmjnpl}["celular"];
$vilxid = "administrador";
$xufwdf = "administrador";
echo "\" placeholder=\"Celular\" required=\"required\">\n</div>\n</div>\n</div>\n<div class=\"col-md-6 col-12\">\n<div class=\"mb-1\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Texto da LOGO</a></label>\n<div class=\"input-group input-group-merge\">\n<span class=\"input-group-text\"><i data-feather='linkedin'></i></span>\n<input type=\"text\" name=\"site\" id=\"site\" minlength=\"3\" maxlength=\"11\" value=\"";
echo ${$cgshjnmhwmc}["site"];
echo "\" class=\"form-control\">\n</div>\n</div>\n</div>\n<div class=\"col-md-6 col-12\">\n<div class=\"mb-1\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Senha atual</a></label>\n<div class=\"input-group input-group-merge\">\n<span class=\"input-group-text\"><i data-feather='key'></i></span>\n<input type=\"password\" name=\"senhaantiga\" id=\"senhaantiga\" minlength=\"5\" maxlength=\"15\" placeholder=\"Digite a Senha atual...\" class=\"form-control\">\n</div>\n</div>\n</div>\n<div class=\"col-md-6 col-12\">\n<div class=\"mb-2\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Nova senha</a></label>\n<div class=\"input-group input-group-merge\">\n<span class=\"input-group-text\"><i data-feather='key'></i></span>\n<input type=\"password\" name=\"novasenha\" id=\"novasenha\" minlength=\"5\" maxlength=\"15\" placeholder=\"Digite a Nova Senha...\" class=\"form-control\">\n</div>\n</div>\n</div>\n<div class=\"col-12\">\n<div class=\"mb-1\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Email</a></label>\n<div class=\"input-group input-group-merge\">\n<span class=\"input-group-text\"><i data-feather=\"mail\"></i></span>\n<input type=\"text\" name=\"email\" id=\"email\" minlength=\"10\" maxlength=\"40\" class=\"form-control\" value=\"";
echo $administrador["email"];
echo "\" required>\n</div>\n</div>\n</div>\n<div class=\"col-md-6 col-12\">\n<div class=\"mb-1\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Texto SSH</a> (<a class=\"text-warning\">O texto vai aparecer na hora de criar contas ssh!</a>) <a class=\"text-success\"><span id=\"cont1\"> 500</span></a> Caracteres restante</label>\n<div class=\"input-group input-group-merge\">\n<textarea name=\"textoconatt\" class=\"form-control\" onkeyup=\"limite_textarea1(this.value)\" id=\"texto1\" maxlength=\"500\" rows=\"3\">";
echo ${$GLOBALS["iyvwdogfrgsd"]}["textocon"];
echo "</textarea>\n</div>\n</div>\n</div>\n<div class=\"col-md-6 col-12\">\n<div class=\"mb-1\">\n<label class=\"form-label\" for=\"first-name-icon\"><a class=\"text-info\">Texto revendas</a> (<a class=\"text-warning\">O texto vai aparecer na hora de criar revendas!</a>) <a class=\"text-success\"><span id=\"cont2\"> 500</span></a> Caracteres restante</label>\n<div class=\"input-group input-group-merge\">\n<textarea name=\"textorevatt\" class=\"form-control\" onkeyup=\"limite_textarea2(this.value)\" id=\"texto2\" maxlength=\"500\" rows=\"3\">";
echo $administrador["textorev"];
echo "</textarea>\n</div>\n</div>\n</div>\n<div class=\"col-12 text-center\">\n<button type=\"submit\" class=\"btn btn-success me-1 waves-effect waves-float waves-light\">Salvar</button>\n<button type=\"reset\" class=\"btn btn-danger waves-effect\">Limpar</button>\n</div>\n</div>\n</div>\n</form>\n</div>\n</div>\n</div>\n</section>\n<!-- Input with Icons end -->\n";
