<?php

$GLOBALS["gfikhvhdgti"] = "SQLSelectnoti";
$GLOBALS["uepfmgswb"] = "SQLDelSSH";
$GLOBALS["qehtsnx"] = "SQLSelecthist";
$GLOBALS["notmtgvwx"] = "SQLSelectSSH";
require_once "seguranca.php";
$oszxnh = "SQLSelectSSH";
$GLOBALS["favlmym"] = "SQLSelecthist";
require_once "config.php";
$nwwpbfirf = "SQLSelectSSH";
$GLOBALS["glyyzmmkmz"] = "SQLDelSSH";
require_once "classe.ssh.php";
$mboqttw = "SQLDelSSH";
require_once "funcoes.php";
$xrsjsicmor = "SQLSelecthist";
$SQLSelectSSH = "delete from hist_usuario_ssh_online where hora_conexao < NOW() - INTERVAL 2 DAY";
$SQLSelectSSH = $conn->prepare($SQLSelectSSH);
$SQLSelectSSH->execute();
$SQLSelecthist = "delete from historico_login where data_login < NOW() - INTERVAL 2 DAY";
$GLOBALS["cbtnkxqtkyf"] = "SQLSelectnoti";
$SQLSelecthist = $conn->prepare($SQLSelecthist);
$SQLSelecthist->execute();
$SQLSelectnoti = "delete from notificacoes where data < NOW() - INTERVAL 2 DAY";
$GLOBALS["kkqowgltkz"] = "SQLSelectnoti";
$SQLSelectnoti = $conn->prepare($SQLSelectnoti);
$SQLSelectnoti->execute();
$SQLDelSSH = "update conta_ssh set status='3', apagar='3', id_usuario='0' WHERE  data_validade < NOW() - INTERVAL 1 DAY and data_suspensao < NOW() - INTERVAL 2 DAY and status >= '2'";
$SQLDelSSH = $conn->prepare($SQLDelSSH);
$SQLDelSSH->execute();
