<?php

$GLOBALS["mplkiybp"] = "accessKEY";
$GLOBALS["ioobbssrbc"] = "dataviewatual";
$GLOBALS["copwntc"] = "servidor";
$GLOBALS["mhpcyfercq"] = "valor";
$GLOBALS["urphheoooyh"] = "dataviewpos";
$GLOBALS["mhxxbhqpw"] = "datar";
$GLOBALS["sxpmbqloxm"] = "data_atual";
$GLOBALS["gjnotilm"] = "usermaster";
$GLOBALS["nsiyldyd"] = "SQLMASTER";
$GLOBALS["uytelpqihojo"] = "SQLServidor";
$GLOBALS["tnfdoebmu"] = "contassh";
$xwpznvj = "servidor";
$GLOBALS["gnmbrg"] = "servidor";
$GLOBALS["ncnxyau"] = "contassh";
$GLOBALS["bndfss"] = "SQLSSH";
$GLOBALS["bwonbpou"] = "administrador";
$wpnuig = "usermaster";
require_once "pages/system/funcoes.php";
require_once "pages/system/seguranca.php";
require_once "pages/system/config.php";
$GLOBALS["koofbdi"] = "data_atual";
require_once "pages/system/classe.ssh.php";
$efptlbq = "SQLServidor";
$ptqerq = "SQLAdministrador";
$GLOBALS["mlmcxfywkdme"] = "SQLSSH";
$GLOBALS["qldrjwkcupqi"] = "SQLAdministrador";
$pwmuqdkk = "SQLSSH";
$GLOBALS["nqxvjfrjgjs"] = "SQLAdministrador";
$SQLAdministrador = "SELECT * FROM admin WHERE id_administrador = '1'";
$SQLAdministrador = $conn->prepare($SQLAdministrador);
$SQLAdministrador->execute();
$administrador = $SQLAdministrador->fetch();
protegePaginassh("userssh");
$data_atual = date("Y-m-d H:i:s");
$SQLSSH = "SELECT * FROM conta_ssh WHERE id_usuario_ssh ='" . $_SESSION["usuarioID"] . "'";
$SQLSSH = $conn->prepare($SQLSSH);
$SQLSSH->execute();
$bckrlxgqbm = "SQLMASTER";
$contassh = $SQLSSH->fetch();
$GLOBALS["igaolrwvnd"] = "contassh";
$SQLServidor = "select * from servidor WHERE id_servidor = '" . $contassh["id_servidor"] . "'";
$SQLServidor = $conn->prepare($SQLServidor);
$SQLServidor->execute();
$servidor = $SQLServidor->fetch();
$SQLMASTER = "SELECT * FROM usuario WHERE id_usuario = '" . $contassh["id_usuario"] . "'";
$SQLMASTER = $conn->prepare($SQLMASTER);
$SQLMASTER->execute();
$usermaster = $SQLMASTER->fetch();
$ghpouxvzt = "ipdominio";
if ($contassh["data_validade"] < $data_atual) {
    $GLOBALS["srfucbhsob"] = "dataviewatual";
    $GLOBALS["ccrrbw"] = "contassh";
    $dataviewatual = date("d/m/Y", strtotime($contassh["data_validade"]));
    $datar = date("Y-m-d H:i:s", strtotime("+31 days", strtotime($data_atual)));
    $dataviewpos = date("d/m/Y", strtotime($datar));
} else {
    $GLOBALS["iflrdhywqhfj"] = "datar";
    $swwgfxcjlkbn = "contassh";
    $GLOBALS["sxxymsoycu"] = "dataviewpos";
    $pqpryrndhjq = "datar";
    $rttkbqe = "dataviewatual";
    $dataviewatual = date("d/m/Y", strtotime($contassh["data_validade"]));
    $datar = date("Y-m-d H:i:s", strtotime("+31 days", strtotime($contassh["data_validade"])));
    $dataviewpos = date("d/m/Y", strtotime($datar));
}
${$GLOBALS["tnfdoebmu"]}["acesso"] *= ${$GLOBALS["tnfdoebmu"]}["valorconta"];
$_SESSION["valor"] = ${$GLOBALS["mhpcyfercq"]};
$_SESSION["data"] = ${$GLOBALS["mhxxbhqpw"]};
$_SESSION["loginssh"] = ${$GLOBALS["tnfdoebmu"]}["login"];
$_SESSION["ip_servidor"] = ${$xwpznvj}["ip_servidor"];
$_SESSION["login_server"] = ${$GLOBALS["copwntc"]}["login_server"];
$ttnyuzdkql = "administrador";
$GLOBALS["qsmyjokwtb"] = "contassh";
$_SESSION["senha_server"] = ${$GLOBALS["copwntc"]}["senha"];
echo "<!DOCTYPE html>\n<html class=\"loading bordered-layout\" lang=\"pt-br\" data-layout=\"bordered-layout\" data-textdirection=\"ltr\">\n<!-- BEGIN: Head-->\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui\">\n<meta name=\"description\" content=\"Painel de gerenciamento vpn\">\n<meta name=\"keywords\" content=\"sshplus, painel, vpn, ssh, user, servidor\">\n<meta name=\"author\" content=\"crazy\">\n<title>";
echo ${$GLOBALS["bwonbpou"]}["site"];
echo "</title>\n<link rel=\"apple-touch-icon\" href=\"app-assets/images/ico/apple-icon-120.png\">\n<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"app-assets/images/ico/favicon.ico\">\n<link href=\"https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600\" rel=\"stylesheet\">\n<!-- BEGIN: Vendor CSS-->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/vendors/css/vendors.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/vendors/css/animate/animate.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/vendors/css/extensions/sweetalert2.min.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/plugins/extensions/ext-component-sweet-alerts.css\">\n<!-- BEGIN: Theme CSS-->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/bootstrap.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/bootstrap-extended.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/colors.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/components.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/themes/dark-layout.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/themes/bordered-layout.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/themes/semi-dark-layout.css\">\n<!-- BEGIN: Page CSS-->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/core/menu/menu-types/vertical-menu.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/plugins/forms/form-validation.css\">\n<link rel=\"stylesheet\" type=\"text/css\" href=\"app-assets/css/pages/authentication.css\">\n<!-- END: Page CSS-->\n<!-- BEGIN: Custom CSS-->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\n<!-- END: Custom CSS-->\n</head>\n<script src=\"https://sdk.mercadopago.com/js/v2\"></script>\n<script type=\"text/javascript\">\n//Calling function\nsetTimeout(repeatAjax,5000);\nfunction repeatAjax(){\njQuery.ajax({\n\n          type: \"POST\",\n          url: 'verifyssh.php',\n          dataType: 'text',\n          success: function(resp) {\n          \tif(resp == 'Aprovado')\n          \t{\n              window.location = \"aprovadossh.php\";\n\n                    jQuery('.teste').html(resp);\n                    }\n\n          },\n          complete: function() {\n                setTimeout(repeatAjax,5000); //After completion of request, time to redo it after a second\n             }\n        });\n}\n</script>\n<!-- BEGIN: Body-->\n<body class=\"vertical-layout vertical-menu-modern blank-page navbar-floating footer-static  \" data-open=\"click\" data-menu=\"vertical-menu-modern\" data-col=\"blank-page\">\n<!-- BEGIN: Content-->\n<div class=\"app-content content \">\n<div class=\"content-overlay\"></div>\n<div class=\"header-navbar-shadow\"></div>\n<div class=\"content-wrapper\">\n<div class=\"content-header row\">\n</div>\n<div class=\"content-body\">\n<body class=\"fundodapagina vertical-layout vertical-menu-modern 1-column  navbar-floating footer-static  menu-collapsed blank-page blank-page\" data-open=\"click\" data-menu=\"vertical-menu-modern\" data-col=\"1-column\">\n<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modalLabel\" aria-hidden=\"true\">\n<div class=\"modal-dialog\">\n<div class=\"modal-content\">\n<div class=\"modal-header\">\n</div>\n<div class=\"modal-body\">\n<!-- content goes here -->\n</div>\n</div>\n</div>\n</div>\n<div class=\"auth-wrapper auth-basic px-2\">\n<div class=\"auth-inner my-2\">\n<!-- Login basic -->\n<div class=\"card mb-0\">\n<div class=\"card-body\">\n<h1 class=\"text-primary text-center\"><a class=\"nav-link nav-link-style\"><b>";
$blkbmauqukl = "dataviewpos";
echo $administrador["site"];
echo "</b></a></h1>\n<br>\n<h2 class=\"card-text mb-1 text-center text-danger\">\xf0\x9f\x91\x8b Ol\xc3\xa1, vamos renovar?</h2><br>\n<h4 class=\"card-text mb-2 text-center text-info\">REVENDA SSH: <span class=\"badge badge-light-warning\">";
echo ${$GLOBALS["gjnotilm"]}["nome"];
echo "</span></h4>\n<h4 class=\"card-text mb-2 text-center text-info\">CONTA SSH: <span class=\"badge badge-light-warning\">";
echo $contassh["login"];
echo "</span></h4>\n<h4 class=\"card-text mb-2 text-center text-info\">LIMITE ACESSO: <span class=\"badge badge-light-warning\">";
echo ${$GLOBALS["ncnxyau"]}["acesso"];
$GLOBALS["gzdrrsdljsq"] = "valor";
echo "</span></h4>\n<h4 class=\"card-text mb-2 text-center text-info\">VALOR UNIT\xc3\x81RIO: <span class=\"badge badge-light-warning\">R\$ ";
echo number_format(${$GLOBALS["tnfdoebmu"]}["valorconta"], 2, ",", ".");
echo "</span></h4>\n<h4 class=\"card-text mb-2 text-center text-info\">VALOR TOTAL: <span class=\"badge badge-light-warning\">R\$ ";
echo number_format($valor, 2, ",", ".");
echo "</span></h4>\n<h4 class=\"card-text mb-2 text-center text-info\">VALIDADE ANTES: <span class=\"badge badge-light-warning\">";
echo ${$GLOBALS["ioobbssrbc"]};
echo "</span></h4>\n<h4 class=\"card-text mb-2 text-center text-info\">VALIDADE DEPOIS: <span class=\"badge badge-light-warning\">";
echo $dataviewpos;
echo "</span></h4><br>\n<div class=\"row\">\n<form role=\"form\" id=\"form\" name=\"form\" action=\"processandossh.php\" method=\"post\">\n<fieldset class=\"form-label-group form-group position-relative has-icon-left\">\n<div class=\"col-12\">\n<div class=\"mb-1 text-center\">\n<label class=\"form-label\" for=\"email-id-column\"><a class=\"badge badge-light-success\">DIGITE O CPF</a></label>\n<div class=\"input-group input-group-merge\">\n<input type=\"text\" minlength=\"11\" maxlength=\"11\" name=\"cpf\" id=\"cpf\" class=\"form-control text-center\" placeholder=\"Favor digitar s\xc3\xb3 n\xc3\xbameros...\" value=\"\" required=\"\"/>\n</div>\n</div>\n</div>\n<input type=\"hidden\" class=\"form-control\" id=\"segmax\" name=\"segmax\" value=\"";
$zbigbreok = "usermaster";
echo ${$GLOBALS["mplkiybp"]};
echo "\"/>\n<input type=\"hidden\" class=\"form-control\" id=\"ipmax\" name=\"ipmax\" value=\"";
echo ${$ghpouxvzt};
echo "\"/>\n<input type=\"hidden\" class=\"form-control\" id=\"apimp\" name=\"apimp\" value=\"";
echo $usermaster["accesstoken"];
echo "\"/>\n<input type=\"hidden\" class=\"form-control\" id=\"nome\" name=\"nome\" value=\"";
$anabqihim = "linha";
echo ${$wpnuig}["nome"];
echo "\"/>\n<input type=\"hidden\" class=\"form-control\" id=\"login\" name=\"login\" value=\"";
echo ${$GLOBALS["tnfdoebmu"]}["login"];
echo "\"/>\n<input type=\"hidden\" class=\"form-control\" id=\"email\" name=\"email\" value=\"";
echo ${$GLOBALS["gjnotilm"]}["email"];
echo "\"/>\n<input type=\"hidden\" class=\"form-control\" id=\"valortotal\" name=\"valortotal\" value=\"";
echo ${$GLOBALS["mhpcyfercq"]};
echo "\"/>\n</fieldset><br>\n<button type=\"submit\" name=\"botaopagar\" class=\"btn btn-success w-100\" tabindex=\"4\"><i data-feather=\"refresh-cw\"></i><b> RENOVAR</b></button><br>\n<a href=\"sairssh.php\" class=\"btn btn-danger w-100\" tabindex=\"4\"><i data-feather=\"log-out\"></i><b> SAIR</b></a>\n</form>\n</div>\n</div>\n<!-- /Login basic -->\n<footer class=\"footer footer-static footer-light mt-5\">\n<div class=\"text-center\">\n<p class=\"clearfix blue-grey lighten-2 mb-0\">\n<span class=\"center\">\nVers\xc3\xa3o: ";
echo $linha;
echo "<br>\n<a class=\"text-bold-800 \" href=\"#\" target=\"_blank\">";
echo ${$GLOBALS["bwonbpou"]}["site"];
echo "&copy; <script>\ndocument.write(new Date().getFullYear())\n</script>.</a><br>Todos os direitos reservados.<br>Seu IP: ";
echo pega_ip();
echo "<br>ISP: ";
$GLOBALS["ivxeeghmebo"] = "isp";
echo $isp;
echo "</span>\n</p>\n</div>\n</footer>\n</div>\n</div>\n</div>\n</div>\n</div>\n<!-- END: Content-->\n<!-- BEGIN: Vendor JS-->\n<script src=\"app-assets/vendors/js/vendors.min.js\"></script>\n<script src=\"app-assets/vendors/js/charts/apexcharts.min.js\"></script>\n<script src=\"app-assets/vendors/js/extensions/tether.min.js\"></script>\n<script src=\"app-assets/js/core/app-menu.js\"></script>\n<script src=\"app-assets/js/core/app.js\"></script>\n<script src=\"app-assets/js/scripts/components.js\"></script>\n<script src=\"app-assets/js/scripts/pages/dashboard-analytics.js\"></script>\n<script src=\"app-assets/js/scripts/extensions/ext-component-sweet-alerts.js\"></script>\n<script src=\"app-assets/vendors/js/extensions/sweetalert2.all.min.js\"></script>\n<script src=\"app-assets/vendors/js/forms/validation/jquery.validate.min.js\"></script>\n<script src=\"app-assets/js/scripts/pages/auth-login.js\"></script>\n<!-- END: Page JS-->\n<script>\n\$(document).ready(function() {\n\$(\"#mybtn\").click(function() {\nvar username = \$(\"#login\").val().trim();\nvar password = \$(\"#senha\").val().trim();\nif (username != \"\" && password != \"\") {\n\$.ajax({\nurl: 'admin/validacao.php',\ntype: 'post',\ndata: {\nusername: username,\npassword: password\n},\nsuccess: function(response) {\nvar msg = \"\";\nif (response == 1) {\nwindow.location = \"home.php\";\n} else {\nSwal.fire({\ntitle: 'Usu\xc3\xa1rio ou senha incorreto!',\nicon: 'error',\nconfirmButtonColor: '#7367f0',\nconfirmButtonText: 'Ok'\n}).then((result) => {\nif (result.isConfirmed) {\nlocation.reload();\n}else{\nlocation.reload();\n}\n})\n}\n}\n});\n}\n});\n});\n\$(window).on('load', function() {\nif (feather) {\nfeather.replace({\nwidth: 14,\nheight: 14\n});\n}\n})\nfunction myFunction() {\nvar x = document.getElementById(\"senha\");\nif (x.type === \"password\") {\nx.type = \"text\";\n} else {\nx.type = \"password\";\n}\n}\ndocument.addEventListener(\"keypress\", function(e) {\nif(e.key === 'Enter') {\nvar btn = document.querySelector(\"#mybtn\");\nbtn.click();\n}\n});\n</script>\n</body>\n<!-- END: Body-->\n</html>\n";
